"""rename department

Revision ID: 267bc90c772e
Revises: 96e1e6ad8de3
Create Date: 2024-10-01 22:48:42.105902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267bc90c772e'
down_revision = '96e1e6ad8de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
